name: Feature Request
description: Suggest an idea for this project
title: "[FR]: "
labels: ["enhancement"]
assignees:
  - TheDesignCraftYT
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe your problem or the reason for this feature request.
      placeholder: Tell us about your reasons!
    validations:
      required: true
  - type: textarea
    id: your-solution
    attributes:
      label: Your Solution
      description: Please describe what you want us to do and what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: something-else
    attributes:
      label: Anything else?
      description: Do you wanna tell us anything else?
    validations:
      required: false